name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: broadway-chatbot
  REGION: asia-south2
  SERVICE: broadway-chatbot             
  REPOSITORY: broadway-chatbot
  WORKLOAD_IDENTITY_PROVIDER: projects/480746037141/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github
  SERVICE_ACCOUNT: github-actions-deploy@broadway-chatbot.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: access_token 

      # Login to Artifact Registry with OAuth access token
      - name: Docker Auth (GAR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        run: |
          DOCKER_IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}"
          DOCKER_TAG="${DOCKER_IMAGE}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show output
        run: echo "${{ steps.deploy.outputs.url }}"
