name: 'Deploy Cloud Functions'
on:
  push:
    branches: [main]
    paths:
      - 'functions/**'
  workflow_dispatch:

env:
  PROJECT_ID: 'broadway-chatbot'
  REGION: 'asia-south2'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/480746037141/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github'
  SERVICE_ACCOUNT: 'github-actions-deploy@broadway-chatbot.iam.gserviceaccount.com'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy imageUpload
        uses: google-github-actions/deploy-cloud-functions@v4
        with:
          name: imageUpload
          entry_point: imageUpload
          runtime: nodejs20
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}
          source_dir: ./functions
          secrets: |-
            GCS_BUCKET_NAME=projects/${{ env.PROJECT_ID }}/secrets/GCS_BUCKET_NAME/versions/latest
            DATABASE_URL=projects/${{ env.PROJECT_ID }}/secrets/PUBLIC_DATABASE_URL/versions/latest

      - name: Deploy storeMemories
        uses: google-github-actions/deploy-cloud-functions@v4
        with:
          name: storeMemories
          entry_point: storeMemories
          runtime: nodejs20
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}
          source_dir: ./functions
          secrets: |-
            DATABASE_URL=projects/${{ env.PROJECT_ID }}/secrets/PUBLIC_DATABASE_URL/versions/latest
            OPENAI_API_KEY=projects/${{ env.PROJECT_ID }}/secrets/OPENAI_API_KEY/versions/latest

      - name: Deploy indexWardrobe
        uses: google-github-actions/deploy-cloud-functions@v4
        with:
          name: indexWardrobe
          entry_point: indexWardrobe
          runtime: nodejs20
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}
          source_dir: ./functions
          secrets: |-
            DATABASE_URL=projects/${{ env.PROJECT_ID }}/secrets/PUBLIC_DATABASE_URL/versions/latest
            OPENAI_API_KEY=projects/${{ env.PROJECT_ID }}/secrets/OPENAI_API_KEY/versions/latest
